<a href="https://colab.research.google.com/github/TivsLThree/CAP-4630-Artificial-Intelligence/blob/master/Homework/HW4/HW4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Create data and import

In [7]:
import numpy as np
from scipy import signal # only used for validation
a = np.matrix('1 2 3 4 5; 0 0 0 0 0; 3 3 3 3 3; 4 4 4 4 4; 1 1 1 1 1')
b = np.matrix('1 0 1; 0 1 0; 1 0 1')
print(conv2d(a, b))
print(signal.convolve2d(a,b, mode = 'valid'))

[[10. 12. 14.]
 [11. 11. 11.]
 [12. 12. 12.]]
[[10 12 14]
 [11 11 11]
 [12 12 12]]


In [8]:
def conv2d(input_mat, kernal_mat):
  kernal_mat = np.rot90(kernal_mat, 2);
  kx,ky = kernal_mat.shape
  if(kx != ky):
    print("Kernal not square!");
    return [];
  if(input_mat.shape[0] < kx or input_mat.shape[1] < kx):
    print("Kernal too large!")
    return [];
  xdiff, ydiff = np.subtract(input_mat.shape,kernal_mat.shape) # figure out the final size
  result_shape = np.add((xdiff,ydiff),(1,1))
  output_mat = np.zeros(result_shape)
  for i in range(xdiff + 1):
    for j in range(ydiff + 1):
       output_mat[i][j] += np.sum(np.multiply(input_mat[i:kx+i,j:ky+j],kernal_mat))
  return output_mat # assuming no relu here


  
print(conv2d(a, b))

[[10. 12. 14.]
 [11. 11. 11.]
 [12. 12. 12.]]


In [9]:

def maxpooling2d(input_mat, s):
  x, y = input_mat.shape
  #if(x != y): testcases supplied allowed this so i will remove it
  #   print("matrix must be square!")
  #   return;
  if(s > x):
    print("s is too large!")
    return;
  nx = (x - s)//s + 1
  ny = (y - s)//s + 1
  output_mat = np.zeros((nx,ny))
  for i in range(nx):
    for j in range(ny):
      sub = input_mat[i*s: i*s + s, j*s : j*s + s]
      max_val = sub.max();
      output_mat[i,j] = max_val
      #f = np.vectorize(lambda x: 0 if x < max_val else max_val)
      #sub = f(sub)
  return output_mat

  
maxpooling2d(a,2)

array([[2., 4.],
       [4., 4.]])